### ISSUE TITLE
Frame cap seems to stop working.

### ISSUE THREAD

**Issue by StochasticTinkr** [xwize/PerformanceTuner#1]
First off: Love the mod, sorry to see the drama on Nexus.  

Anyway, I notice that sometimes the FPS (actual) starts to go way above the configured maximum. I don't have much more info at the moment, but I'll try to figure out when it happens and post more information.

**Comment by xwize** [comment]
Yeah I'm sorry about it too.

The whole thing could've been diffused much sooner and things were said in anger that shouldn't have been said.


Have you downloaded the code and got it building?

________________________________

**Comment by StochasticTinkr** [comment]
Yeah, got it working.  However, I decided to try to completely reinstall FO4.  I've been having some weird issues all over, so thought I'd start fresh.  I'll let you know if I still see this issue.

**Comment by xwize** [comment]
Alright. I left a little overview in the readme.md.

If you have any questions just ask. I can go through any specifics.

I've been updating the download page I figure this area can double up as a support page for people.

It's been very emotionally draining so I'm quite happy now the source is out.
Got me thinking, if someone takes the code and puts their own version on Nexus, that would be pretty funny. Modify it a bit and sneak it on there.

________________________________

**Comment by xwize** [comment]
Seems there was a F4 update recently? There's all kinds of drama on Steam. I tested the mod it seems to still work.

**Comment by StochasticTinkr** [comment]
Bethesda is annoying is all.  Anyway, if I any improvements to this, I'd ask your permission before putting it on Nexus. I'd like to respect your wishes in that regard, but I think it would be good to have it there.  I'd disable all donation, or set it up to donate to you.

**Comment by StochasticTinkr** [comment]
So, I figured out the issue, and its kind of silly.  The ConfigAdjust code you have was switching me to simple mode when I accidentally crouched and pressed down at the same time.  Now that I know the problem, I can avoid it.
