### ISSUE TITLE
Can't get ReShade 3.0.8 fully working along side DPT.

### ISSUE THREAD

**Issue by ghost** [xwize/PerformanceTuner#2]
When I install it like said in the readme, I can get the ReShade overlay up, but it doesn't see the shaders downloaded with it. The config window is completely empty of shaders, is there something else I need to do?

Thanks for the amazing mod.

**Comment by xwize** [comment]
I think there’s an ini that comes with reshade (dxgi.ini?), you have to rename it to match the newly named dll.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by ghost** [comment]
Yep simple as that, I could have figure that out, my bad. Good idea to include that in the readme though as well next time. Thanks.
